trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'pucpr-estudantes-turma-A-grupo-4'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'pucpr-estudantes_BES_2026_1SEM_7A_EQ02'
    cliProjectName: 'BES_2026_1SEM_7A_EQ02'
    extraProperties: |
      sonar.sources=.
      sonar.exclusions=azure-pipelines.yml,README.md

- script: |
    echo "Projeto estático HTML/CSS/JS - sem etapa de build"
  displayName: 'Validate project'

- task: SonarCloudAnalyze@3
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'