trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '20.x'
  SONAR_SERVICE_CONNECTION: 'SonarCloud'
  SONAR_ORGANIZATION: 'pucpr-estudantes-turma-a-grupo-4'
  SONAR_PROJECT_KEY: 'pucpr-estudantes_BES_2026_1SEM_7A_EQ02'
  SONAR_PROJECT_NAME: 'BES_2026_1SEM_7A_EQ02'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Use Node.js $(NODE_VERSION)'

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: '$(SONAR_SERVICE_CONNECTION)'
    organization: '$(SONAR_ORGANIZATION)'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'
    cliProjectName: '$(SONAR_PROJECT_NAME)'
    extraProperties: |
      sonar.sources=public,server.js
      sonar.tests=tests
      sonar.javascript.lcov.reportPaths=coverage/lcov.info
      sonar.exclusions=**/node_modules/**,coverage/**,package-lock.json,README.md
  displayName: 'Prepare SonarQube Cloud analysis'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run check
  displayName: 'Check Node.js syntax'

- script: npm test
  displayName: 'Run tests with coverage'

- task: SonarCloudAnalyze@3
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'